apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  password: dHJhaW53aXRoc2h1YmhhbQ==   #base64 encoded for "root"


  # base64  - use to convert secret to binary
  # echo "root" | base64
