kind: Service  # Service file for statefulset
apiVersion: v1
metadata:
  name: mysql-service 
  namespace: mysql
spec:
  clusterIP: None
  selector
    app: mysql   # Use the appropriate label to match your pod
  ports:
    - name: mysql
      protocol: TCP
      port: 3306    # Port in the service
      targetPort: 3306 # Port in the pod
  type: ClusterIP
